# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Backend CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B package --file BackEnd/sept-backend/pom.xml
      - run: mkdir staging && cp BackEnd/sept-backend/target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: backend_package
          path: staging

